version: '3'

services:
  redis01:
    container_name: redis01
    build: ./redis
    networks:
      - host
    env_file:
      - './redis/env/master_variables.env'
  

  redis02:
    container_name: redis02
    build: ./redis
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'
    

  redis03:
    container_name: redis03
    build: ./redis
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'
  
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    networks:
      - host
  proxy:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '8080:80'

networks:
  host:
