version: '3'

services:
  redis01:
    container_name: redis01
    build: ./redis
    ports:
      - 6379:6379
    networks:
      - host
    env_file:
      - './redis/env/master_variables.env'

  redis02:

    container_name: redis02
    build: ./redis
    ports:
      - 6380:6379
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'

  redis03:
    container_name: redis03
    build: ./redis
    ports:
      - 6381:6379
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'

  proxy:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '8888:9000'
      - '8080:80'

networks:
  host:
