version: '3'

services:
  redis01:
    container_name: redis01
    build: ./redis
    networks:
      - host
    env_file:
      - './redis/env/master_variables.env'
    volumes: 
      - "./logs/redis.log:/var/log/sentinel.log"

  redis02:
    container_name: redis02
    build: ./redis
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'
    volumes: 
      - "./logs/redis.log:/var/log/sentinel.log"

  redis03:
    container_name: redis03
    build: ./redis
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'
    volumes: 
      - "./logs/redis.log:/var/log/sentinel.log"
  proxy:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '8080:80'

networks:
  host:
